import {Header} from "../components/Header"
import { ListProducts } from "../components/ListProducts"
import {Title} from "../components/Title"

const BasicLayout = () => {
  return (
    <>
      <Header/>
      <Title/>
      <ListProducts/>
      <div>
        <h1>Basic Laoyut</h1>
        <h5>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero, enim distinctio id mollitia voluptas consectetur nemo saepe minus dolore quasi laudantium porro facilis, dolores dolor? Rerum blanditiis iure cupiditate delectus dolore amet eveniet vel, earum ipsum tempore quo quam dicta id, eos quia repellat quas ipsa, ut assumenda adipisci atque?</h5>
        <h5>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quisquam maiores ab harum illum, atque in mollitia doloribus officia facere accusantium rem dolores tempora numquam molestias necessitatibus eum perspiciatis? Perferendis, a. Earum ullam quis cum ut commodi perspiciatis, consequatur labore perferendis nesciunt quos aut, molestias minima temporibus obcaecati id vero exercitationem sequi! Magni quo sapiente optio non? Dolore, eligendi dignissimos libero at consequatur voluptates praesentium perspiciatis vero in officia quae blanditiis? Ratione laudantium recusandae, magnam consequatur maiores modi! Quaerat delectus ut laboriosam accusamus distinctio exercitationem libero quas error natus dolor praesentium dolorum, corrupti dicta reprehenderit unde? Culpa dolorem suscipit voluptas cum quo saepe facilis, laboriosam eveniet repellendus ea repudiandae magni vero aspernatur dolores earum rem sed sapiente officia doloremque, veniam fugit assumenda enim quis. Aperiam eius libero aliquam itaque, accusantium provident accusamus doloribus dolore maiores quisquam facilis rerum a expedita necessitatibus suscipit commodi! Iste rerum optio quis voluptatibus error ullam explicabo dicta ipsum, libero deserunt quos atque cum delectus nulla? Unde deserunt enim placeat, architecto temporibus atque doloremque laudantium deleniti distinctio. Amet hic maiores dignissimos dolore optio incidunt soluta blanditiis aliquid, impedit ipsum. Aliquam molestias at consequuntur sapiente reiciendis consectetur facilis, dolor repellat quidem dicta animi quae laboriosam voluptas doloremque voluptatibus deleniti commodi nam assumenda ut eos inventore perspiciatis. Exercitationem assumenda rem placeat ut omnis totam quis cupiditate excepturi odio dignissimos, nesciunt voluptatum hic tempora corporis deleniti, asperiores laboriosam ducimus itaque ipsam doloremque aliquam enim et. Error iusto vero tempore rerum placeat tenetur, illum mollitia nobis non porro, voluptatum eum ducimus nam eos reprehenderit maxime ratione? Neque odit dolore rem nihil dolorum quas optio distinctio vitae tempore at beatae, perferendis ab fugiat id corrupti rerum saepe deleniti tenetur a repellendus blanditiis. Odit eum eaque sunt impedit expedita. Aspernatur deserunt autem et. Consequuntur a ipsam corporis eius temporibus exercitationem hic molestias at!</h5>
        <h5>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quisquam maiores ab harum illum, atque in mollitia doloribus officia facere accusantium rem dolores tempora numquam molestias necessitatibus eum perspiciatis? Perferendis, a. Earum ullam quis cum ut commodi perspiciatis, consequatur labore perferendis nesciunt quos aut, molestias minima temporibus obcaecati id vero exercitationem sequi! Magni quo sapiente optio non? Dolore, eligendi dignissimos libero at consequatur voluptates praesentium perspiciatis vero in officia quae blanditiis? Ratione laudantium recusandae, magnam consequatur maiores modi! Quaerat delectus ut laboriosam accusamus distinctio exercitationem libero quas error natus dolor praesentium dolorum, corrupti dicta reprehenderit unde? Culpa dolorem suscipit voluptas cum quo saepe facilis, laboriosam eveniet repellendus ea repudiandae magni vero aspernatur dolores earum rem sed sapiente officia doloremque, veniam fugit assumenda enim quis. Aperiam eius libero aliquam itaque, accusantium provident accusamus doloribus dolore maiores quisquam facilis rerum a expedita necessitatibus suscipit commodi! Iste rerum optio quis voluptatibus error ullam explicabo dicta ipsum, libero deserunt quos atque cum delectus nulla? Unde deserunt enim placeat, architecto temporibus atque doloremque laudantium deleniti distinctio. Amet hic maiores dignissimos dolore optio incidunt soluta blanditiis aliquid, impedit ipsum. Aliquam molestias at consequuntur sapiente reiciendis consectetur facilis, dolor repellat quidem dicta animi quae laboriosam voluptas doloremque voluptatibus deleniti commodi nam assumenda ut eos inventore perspiciatis. Exercitationem assumenda rem placeat ut omnis totam quis cupiditate excepturi odio dignissimos, nesciunt voluptatum hic tempora corporis deleniti, asperiores laboriosam ducimus itaque ipsam doloremque aliquam enim et. Error iusto vero tempore rerum placeat tenetur, illum mollitia nobis non porro, voluptatum eum ducimus nam eos reprehenderit maxime ratione? Neque odit dolore rem nihil dolorum quas optio distinctio vitae tempore at beatae, perferendis ab fugiat id corrupti rerum saepe deleniti tenetur a repellendus blanditiis. Odit eum eaque sunt impedit expedita. Aspernatur deserunt autem et. Consequuntur a ipsam corporis eius temporibus exercitationem hic molestias at!</h5>
        <h5>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quisquam maiores ab harum illum, atque in mollitia doloribus officia facere accusantium rem dolores tempora numquam molestias necessitatibus eum perspiciatis? Perferendis, a. Earum ullam quis cum ut commodi perspiciatis, consequatur labore perferendis nesciunt quos aut, molestias minima temporibus obcaecati id vero exercitationem sequi! Magni quo sapiente optio non? Dolore, eligendi dignissimos libero at consequatur voluptates praesentium perspiciatis vero in officia quae blanditiis? Ratione laudantium recusandae, magnam consequatur maiores modi! Quaerat delectus ut laboriosam accusamus distinctio exercitationem libero quas error natus dolor praesentium dolorum, corrupti dicta reprehenderit unde? Culpa dolorem suscipit voluptas cum quo saepe facilis, laboriosam eveniet repellendus ea repudiandae magni vero aspernatur dolores earum rem sed sapiente officia doloremque, veniam fugit assumenda enim quis. Aperiam eius libero aliquam itaque, accusantium provident accusamus doloribus dolore maiores quisquam facilis rerum a expedita necessitatibus suscipit commodi! Iste rerum optio quis voluptatibus error ullam explicabo dicta ipsum, libero deserunt quos atque cum delectus nulla? Unde deserunt enim placeat, architecto temporibus atque doloremque laudantium deleniti distinctio. Amet hic maiores dignissimos dolore optio incidunt soluta blanditiis aliquid, impedit ipsum. Aliquam molestias at consequuntur sapiente reiciendis consectetur facilis, dolor repellat quidem dicta animi quae laboriosam voluptas doloremque voluptatibus deleniti commodi nam assumenda ut eos inventore perspiciatis. Exercitationem assumenda rem placeat ut omnis totam quis cupiditate excepturi odio dignissimos, nesciunt voluptatum hic tempora corporis deleniti, asperiores laboriosam ducimus itaque ipsam doloremque aliquam enim et. Error iusto vero tempore rerum placeat tenetur, illum mollitia nobis non porro, voluptatum eum ducimus nam eos reprehenderit maxime ratione? Neque odit dolore rem nihil dolorum quas optio distinctio vitae tempore at beatae, perferendis ab fugiat id corrupti rerum saepe deleniti tenetur a repellendus blanditiis. Odit eum eaque sunt impedit expedita. Aspernatur deserunt autem et. Consequuntur a ipsam corporis eius temporibus exercitationem hic molestias at!</h5>
      </div>
    </>
  )
}

export default BasicLayout